import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={GeistMono.variable}>
      {/* Use className (not only variable) to force Geist Sans */}
      <body className={`${GeistSans.className} font-sans antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
